name: KREAM-sele

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        ref: main
    - name: Setup Python
      uses: actions/setup-python@v1
      with:
          python-version: '3.x'
          architecture: 'x64'
    
    - name: Install python package # 파이썬 관련 패키지를 설치하고
      run: |        
        pip install selenium
        pip install requests  
        pip install webdriver-manager      
    
    - name: Install ubuntu package # 우분투 관련 패키지도 설치한 후
      run: |        
        sudo apt-get install fonts-unfonts-core
        sudo apt-get install fonts-unfonts-extra
        wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add        
        sudo apt-get install google-chrome-stable    
        wget https://chromedriver.storage.googleapis.com/2.40/chromedriver_linux64.zip
        unzip ./chromedriver_linux64.zip   
      
    - name: Run! # send_to_weather.py 파일을 실행하시오! 
      run: | 
        python ./kream_card_wallet.py 